"""Corrected French + American English translation, phrase by phrase, tied to the original cues.

Each entry: (first_cue, last_cue, corrected French, English). The phrase keeps the timing of its cues,
so the corrected French SRT, the English SRT and the dub all stay in sync with the video.
Cue numbers refer to source/YOUTUBE_VIDEO_FR.srt. Cues 392-393 are dropped (see NOTES).
"""

NOTES = [
    "Cue 1: removed the transcription watermark '(Transcrit par TurboScribe…)'.",
    "Cues 392-393: a repeat of 'Si vous avez des questions…' squeezed into 0.98 s, almost certainly a "
    "transcription duplicate; dropped from the subtitles and the dub.",
]

SEGMENTS = [
    (1, 2, "Bonjour à tous et à toutes, aujourd'hui on se retrouve pour une nouvelle vidéo YouTube",
     "Hey everyone, today we're back with a brand-new YouTube video,"),
    (3, 6, "excellente, puisqu'aujourd'hui on va créer ni plus ni moins qu'un setter IA qui va être branché sur notre Instagram et qui va nous ramener des calls dans notre calendrier,",
     "and it's a great one, because today we're building nothing less than an AI setter that plugs right into our Instagram and brings calls straight into our calendar."),
    (7, 7, "c'est aussi simple que ça.",
     "It's as simple as that."),
    (8, 8, "Alors, pourquoi cette vidéo ?",
     "So why this video?"),
    (9, 15, "Parce qu'aujourd'hui, je vois énormément de tutoriels dans les communautés, ou même sur YouTube, qui nous apprennent à faire des flows ManyChat pour créer des setters IA. Et le problème, c'est que la plupart du temps, les setters IA que l'on nous montre ressemblent à ça.",
     "Because these days, I see a ton of tutorials in communities, or even on YouTube, that teach you how to build ManyChat flows to create AI setters. And the problem is, most of the time, the AI setters they show you look like this."),
    (16, 21, "Très clairement, personne sur cette planète n'a assez d'énergie ni de temps pour entretenir ce genre de scénario tout en se concentrant sérieusement sur l'aspect sales, sur l'aspect setting et sur les performances de notre setter IA en matière de prise de rendez-vous.",
     "Let's be honest: nobody on this planet has the energy or the time to maintain a scenario like this and still seriously focus on the sales side, the setting side, and how well our AI setter actually performs at booking calls."),
    (22, 26, "Donc ce que je vous propose aujourd'hui, c'est de vous montrer une méthode super simple qui va vous permettre, en à peine neuf minutes, de créer le meilleur setter IA que vous ayez jamais utilisé.",
     "So today, I'm going to show you a super simple method that lets you build, in barely nine minutes, the best AI setter you've ever used."),
    (27, 27, "Vous êtes prêts ?",
     "You ready?"),
    (28, 28, "C'est parti !",
     "Let's go!"),
    (29, 32, "Étape numéro 1 : avoir un compte ManyChat, bien évidemment, un compte Instagram pour pouvoir le tester, et un Calendly.",
     "Step one: you need a ManyChat account, obviously, an Instagram account to test it with, and a Calendly."),
    (33, 37, "Une fois que vous avez ça, vous allez vous rendre sur ce site, il s'appelle manysetter.com. Vous aurez le lien dans la description ci-dessous, et il va vous permettre de créer votre setter gratuitement.",
     "Once you've got that, head over to this site. It's called manysetter.com. You'll find the link in the description below, and it lets you create your setter for free."),
    (38, 40, "Donc ce qui est ultra bien, c'est que vous allez pouvoir tout gérer depuis ce site-là.",
     "What's really great is that you can manage everything from this one site."),
    (41, 49, "Vous allez sortir toute la partie sales, et toute la partie qui fait le cœur du setting, en dehors de ManyChat, et c'est ce qui va rendre le flow tellement simple que vous n'aurez plus besoin que de deux étapes, au lieu des mille et une étapes et des mille et une conditions que l'on a d'habitude dans un flow ManyChat.",
     "You're taking the whole sales part, everything at the core of setting, out of ManyChat. And that's what makes the flow so simple: you'll only need two steps, instead of the thousand and one steps and thousand and one conditions you usually have in a ManyChat flow."),
    (50, 51, "Donc on commence directement : on va cliquer sur « Create my ManyChat setter ».",
     "So let's jump right in. We're going to click on Create my ManyChat setter."),
    (52, 54, "Une fois que vous avez cliqué là-dessus, vous allez être redirigé vers une page de connexion.",
     "Once you click that, you'll be redirected to a login page."),
    (55, 59, "En l'occurrence, je suis déjà connecté, mais vous allez tout simplement entrer votre email, puis recevoir un code que vous allez récupérer dans votre boîte mail et coller dans ManySetter.",
     "In my case, I'm already logged in, but you'll just enter your email and get a code, which you'll grab from your inbox and paste into ManySetter."),
    (60, 61, "Une fois que c'est fait, vous allez tout simplement créer un nouveau workspace.",
     "Once that's done, you'll simply create a new workspace."),
    (62, 62, "Donc pour la démo, je vais l'appeler",
     "For the demo, I'll call it"),
    (63, 63, "« ManyChat Test ».",
     "ManyChat Test."),
    (64, 64, "Tout simplement. Je crée le workspace.",
     "Nice and simple. I create the workspace."),
    (65, 66, "À partir de ce moment-là, ManySetter nous propose de créer directement notre setter.",
     "From there, ManySetter offers to create our setter right away."),
    (67, 67, "Donc allons-y.",
     "So let's go."),
    (68, 72, "Nous cliquons sur « Setup setter », et une fois que c'est fait, l'application va vous poser une question assez pertinente : est-ce que vous faites du setting pour un client ou pour votre propre business ?",
     "We click on Setup setter, and once that's done, the app asks you a pretty relevant question: are you setting for a client, or for your own business?"),
    (73, 74, "Nous, en l'occurrence, c'est pour notre propre business, donc nous cliquons là-dessus.",
     "In our case, it's for our own business, so we click on that."),
    (75, 75, "Nous voulons créer un setter sur Instagram.",
     "We want to create a setter on Instagram."),
    (76, 77, "Donc pour l'exemple, nous allons l'appeler « Instagram setter ».",
     "So for this example, we'll call it Instagram setter."),
    (78, 80, "Je clique sur « Suivant », et là, on arrive à la connexion avec ManyChat, ce qui va rendre l'utilisation encore plus simple.",
     "I click Next, and now we get to the ManyChat connection, which makes it even easier to use."),
    (81, 83, "Tout simplement, vous avez ici des vidéos que vous pouvez regarder, mais moi, je vais vous le montrer directement ici.",
     "Basically, there are videos here you can watch, but I'll just show you right here."),
    (84, 86, "Vous allez cliquer sur « Copier » pour récupérer le code, puis cliquer sur « Install in ManyChat ».",
     "You click Copy to grab the code, then click Install in ManyChat."),
    (87, 89, "Là, une page va s'ouvrir, la page de ManyChat, qui va vous proposer directement d'installer l'application.",
     "A page opens, the ManyChat page, offering to install the app right away."),
    (90, 91, "Vous avez juste à cliquer sur le bouton « Installer », en dessous.",
     "You just have to click the Install button below."),
    (92, 94, "Ici, on nous demande sur quel compte on veut installer notre setter IA.",
     "Here, it asks which account we want to install our AI setter on."),
    (95, 97, "Vous allez sélectionner le vôtre, bien entendu, celui sur lequel vos réseaux sont connectés.",
     "You'll select yours, of course, the one with your social accounts connected."),
    (98, 100, "Aujourd'hui, ce tutoriel porte sur Instagram, mais vous allez aussi pouvoir l'utiliser sur WhatsApp, Telegram, Messenger, et Instagram, bien entendu.",
     "Today's tutorial is about Instagram, but you can also use it on WhatsApp, Telegram, Messenger, and Instagram, of course."),
    (101, 103, "Donc vous cliquez sur « Installer », et là, directement, vous allez voir que ManyChat nous dit que l'application a bien été installée.",
     "So you click Install, and right away, you'll see ManyChat telling us the app has been installed."),
    (104, 107, "Vous allez vous rendre dans les paramètres de l'app, et c'est dans ces paramètres que nous allons coller le code de ManySetter.",
     "Now go to the app settings: that's where we're going to paste the ManySetter code."),
    (108, 109, "Une fois que le code est collé, vous allez pouvoir cliquer sur « Save ».",
     "Once the code is pasted, you can click Save."),
    (110, 111, "Parfait, comme vous pouvez le voir, tout a bien été sauvegardé.",
     "Perfect. As you can see, everything's been saved."),
    (112, 113, "Maintenant, ManySetter est connecté à votre ManyChat.",
     "Now ManySetter is connected to your ManyChat."),
    (114, 116, "Donc nous retournons sur la configuration de notre workspace, et hop, comme vous pouvez le voir, ManySetter est bien connecté.",
     "So we go back to our workspace setup, and boom, as you can see, ManySetter is connected."),
    (117, 119, "Maintenant, ManySetter nous dit qu'il faut ajouter ManySetter dans un flow ManyChat.",
     "Now ManySetter tells us we need to add ManySetter to a ManyChat flow."),
    (120, 121, "C'est super intéressant, puisque c'est là que tout va se jouer.",
     "This is the really interesting part, because that's where it all happens."),
    (122, 124, "Au lieu de devoir utiliser des milliers de modules, des milliers d'applications, nous allons juste nous rendre dans nos automatisations.",
     "Instead of using thousands of modules and thousands of apps, we're just going to head into our automations."),
    (125, 127, "Comme vous pouvez le voir, j'ai créé un flow plus que basique pour faire le test aujourd'hui.",
     "As you can see, I've built a super basic flow for today's test."),
    (128, 132, "Et ce flow-là consiste tout simplement à détecter si un utilisateur sur Instagram nous envoie un message contenant l'une de ces lettres, pour répondre à tout le monde, bien évidemment, dans le cadre du test.",
     "This flow simply detects whether someone on Instagram sends us a message containing any of these letters, so it replies to everyone, just for the purpose of the test."),
    (133, 134, "Donc, comme on peut le voir ici, nous allons supprimer directement « Send Message ».",
     "So, as you can see here, we're going to delete Send Message right away."),
    (135, 135, "Voilà, et nous allons choisir une autre étape.",
     "There we go. Now we'll choose another step."),
    (136, 136, "Nous allons tout simplement cliquer sur « Action », ici.",
     "We're simply going to click on Action, right here."),
    (137, 137, "Donc je clique.",
     "So I click."),
    (138, 140, "Automatiquement, vous allez pouvoir cliquer sur « Action », juste ici, et sélectionner, comme vous pouvez le voir, l'application qui est directement proposée.",
     "Then you can click on Action right here and select, as you can see, the app that's suggested right there."),
    (141, 141, "Il n'y a pas plus simple.",
     "It doesn't get any simpler."),
    (142, 142, "Vous cliquez sur « Start conversation ».",
     "You click Start conversation."),
    (143, 145, "Et une fois que c'est fait, ManySetter va vous proposer quelques champs, notamment le canal que vous allez utiliser.",
     "Once that's done, ManySetter shows you a few fields, including the channel you're going to use."),
    (146, 146, "En l'occurrence, pour nous, ça va être Instagram.",
     "In our case, it's Instagram."),
    (147, 149, "Donc on clique ici, et on va sélectionner notre setter, qui est juste ici : « Instagram Setter ».",
     "So we click here and select our setter, which is right here: Instagram Setter."),
    (150, 151, "Une fois que c'est fait, vous allez cliquer sur « Save », et juste ici, « Update ».",
     "Once that's done, click Save, and right here, Update."),
    (152, 152, "Parfait.",
     "Perfect."),
    (153, 153, "Tout est maintenant connecté.",
     "Everything's connected now."),
    (154, 156, "Nous allons juste retourner sur ManySetter pour voir comment il réagit à ça.",
     "Let's just go back to ManySetter and see how it reacts."),
    (157, 157, "C'est parfait.",
     "That's perfect."),
    (158, 158, "Maintenant, nous allons pouvoir cliquer sur « Continue ».",
     "Now we can click Continue."),
    (159, 162, "Une fois que vous avez cliqué sur « Continue », on voit que l'application nous demande où l'on veut recevoir nos appels.",
     "Once you've clicked Continue, the app asks where we want to receive our calls."),
    (163, 167, "Tout simplement, là, vous pouvez choisir d'intégrer vos outils, pour que le setter, rien qu'en parlant avec votre lead, puisse booker l'appel à sa place, au lieu de le renvoyer vers un lien.",
     "Basically, here you can choose to integrate your tools, so the setter, just by talking with your lead, can book the call for them instead of sending them a link."),
    (168, 171, "En l'occurrence, pour garder ce tuto beaucoup plus court, et ne pas montrer de clés d'API dans ce tutoriel, je vais tout simplement utiliser un lien.",
     "In this case, to keep this tutorial much shorter and avoid showing any API keys, I'm just going to use a link."),
    (172, 174, "Donc je clique sur « Other link », et je vais aller directement dans mon Calendly, juste ici, pour récupérer mon lien.",
     "So I click Other link, and I'll go straight to my Calendly, right here, to grab my link."),
    (175, 175, "Voilà.",
     "There we go."),
    (176, 177, "Je clique sur « Copier le lien », je reviens dans ManySetter et je colle.",
     "I click Copy link, go back to ManySetter, and paste it."),
    (178, 180, "Une fois que c'est fait, vous pouvez voir directement sur votre écran qu'on vous propose des follow-ups.",
     "Once that's done, you'll see right on your screen that it offers you follow-ups."),
    (181, 181, "Vous avez donc plusieurs choix.",
     "So you have a couple of options."),
    (182, 184, "Soit vous les activez, soit vous les désactivez, et on verra un peu plus tard comment les personnaliser.",
     "Either you turn them on or you turn them off, and we'll see a bit later how to customize them."),
    (185, 188, "Mais comme vous pouvez le voir, sur votre gauche, il y a un onglet dont on ne s'est pas encore servi, qui s'appelle « Offer & fit ».",
     "But as you can see on your left, there's a tab we haven't used yet, called Offer and fit."),
    (189, 189, "Je vous invite à cliquer dessus.",
     "Go ahead and click on it."),
    (190, 190, "Et là, ça va être super simple.",
     "And this part is super simple."),
    (191, 195, "Vous allez pouvoir écrire votre offre, écrire ce que vous vendez, ce que vous voulez proposer, et donner du contexte pour que tout votre script de setting et tout votre setter IA soient au courant de ce que vous faites.",
     "You can write your offer, what you sell, what you want to offer, and give some context, so your whole setting script and your AI setter know exactly what you do."),
    (196, 196, "Donc moi, par exemple, je vais écrire : « I",
     "So for example, I'm going to type:"),
    (197, 197, "sell to help people in e-com",
     "I sell to help people in e-com"),
    (198, 198, "enrich their e-commerce with winner products. »",
     "grow their e-commerce business with winning products."),
    (199, 201, "Comme vous le voyez ici, vous pouvez ajouter des liens, des PDF, tout ce qui convient à votre business, finalement.",
     "As you can see here, you can add links, PDFs, really anything that fits your business."),
    (202, 203, "Ensuite, vous allez pouvoir ajouter ici des critères, qui ne sont pas obligatoires, mais vous pouvez",
     "Next, you can add some criteria here. They're optional, but you can,"),
    (204, 205, "par exemple mettre « I can invest 3k » et « not a full beginner ».",
     "for example, put I can invest 3K, and not a full beginner."),
    (206, 208, "Et une fois que vous avez rempli vos informations, vous allez tout simplement pouvoir cliquer sur « Continue ».",
     "And once you've filled in your info, you can simply click Continue."),
    (209, 213, "Et ici, comme vous pouvez le voir, il y a un chargement qui va se lancer pour générer directement votre script de setting, ainsi que tout le contexte dont il va avoir besoin pour être le meilleur setter IA.",
     "And here, as you can see, a loading process kicks off to generate your setting script right away, along with all the context it needs to be the best AI setter possible."),
    (214, 217, "Généralement, ça prend entre une et trois minutes, ce n'est pas très long, mais comme vous pouvez le voir, tout est en train de se charger.",
     "It usually takes between one and three minutes, so it's not very long, but as you can see, everything's loading."),
    (218, 218, "Et voilà le playbook, enfin terminé.",
     "And here's the playbook, finally done."),
    (219, 220, "Vous allez pouvoir cliquer sur « Continue » et finir le setup de votre workspace.",
     "You can click Continue and finish setting up your workspace."),
    (221, 222, "Donc comme vous pouvez le voir, ici, vous pouvez directement essayer votre setter.",
     "As you can see, right here, you can try out your setter right away."),
    (223, 224, "Alors c'est super, parce que vous allez pouvoir écrire, et vous allez ainsi",
     "This is awesome, because you can type something in"),
    (225, 225, "pouvoir discuter avec votre setter.",
     "and actually chat with your setter."),
    (226, 228, "Et là, comme on peut le voir, les questions sont déjà très intéressantes, et vous pouvez continuer à discuter avec lui.",
     "And as you can see, the questions are already really good, and you can keep chatting with it."),
    (229, 231, "Si vous n'aimez pas les réponses qu'il vous donne, vous pouvez cliquer directement ici, dans ce petit espace, et demander par exemple",
     "If you don't like the answers it gives you, you can click right here, in this little box, and ask, for example,"),
    (232, 233, "et écrire ici : « I want a better tone with emoji, face and hands. »",
     "type in here: I want a better tone, with emojis, faces and hands."),
    (234, 236, "Vous pouvez directement envoyer votre message, et vous allez pouvoir améliorer votre script au fur et à mesure.",
     "You can send your message right away and keep improving your script as you go."),
    (237, 239, "Comme on peut le voir, le script de setting s'est bien mis à jour, et si je repose la question,",
     "As you can see, the setting script has been updated. So if I ask the question again,"),
    (240, 241, "hop, il me répond avec les mises à jour appliquées automatiquement.",
     "boom, it answers with the updates applied automatically."),
    (242, 244, "Avec cet outil, vous avez directement 14 jours d'essai gratuit, donc vous pouvez tout à fait le tester sur vos premiers leads.",
     "With this tool, you get a 14-day free trial right away, so you can totally test it on your first leads."),
    (245, 246, "Vous avez 500 réponses IA, donc vous pouvez largement tester et obtenir vos premiers appels.",
     "You get 500 AI replies, so you've got plenty to test with and land your first calls."),
    (247, 249, "Et on va faire le tour très rapidement, pour que vous puissiez comprendre à quoi ça sert.",
     "Let's take a quick tour so you can see what everything does."),
    (250, 253, "Comme vous pouvez le voir ici, on a l'historique de ce qu'on lui a demandé, pour qu'il s'entraîne et qu'il devienne un meilleur setter.",
     "As you can see here, we have the history of everything we asked it, so it can train and become a better setter."),
    (254, 256, "Donc vous pourrez toujours le tester ici avant de le brancher sur vos clients ou sur votre compte Instagram.",
     "So you can always test it here before plugging it into your clients' accounts or your own Instagram."),
    (257, 260, "Et vous allez retrouver ici, dans l'onglet « Playbook », absolument tout ce qui est lié au script de setting.",
     "And here in the Playbook tab, you'll find absolutely everything related to the setting script."),
    (261, 264, "Vous avez votre script de setting, qui est juste ici, vous avez l'offre, les critères, votre voix, les objections, le contexte, absolument tout.",
     "You've got your setting script right here, your offer, the criteria, your voice, the objections, the context, absolutely everything."),
    (265, 267, "Je vous laisserai regarder ce que l'IA a généré pour vous, mais globalement, vous allez avoir des rendez-vous qualifiés.",
     "I'll let you look through what the AI generated for you, but overall, you're going to get qualified appointments."),
    (268, 270, "Quand vous allez ici, dans l'onglet « Booking & follow-ups », vous pouvez connecter votre calendrier",
     "When you go here, into the Booking and follow-ups tab, you can connect your calendar"),
    (271, 273, "beaucoup plus en profondeur qu'avec un simple lien de réservation : vous allez pouvoir mettre la clé API de votre calendrier.",
     "much more deeply than with a simple booking link, by adding your calendar's API key."),
    (274, 274, "Mais ça, on l'a déjà fait.",
     "But we've already done that."),
    (275, 277, "Vous pouvez voir ici les follow-ups, qui sont beaucoup plus complets que ce que l'on avait dans l'onboarding.",
     "Here you can see the follow-ups, which are much more complete than what we had during onboarding."),
    (278, 281, "Parce qu'ici, vous pouvez non seulement laisser l'IA écrire le follow-up que vous voulez, dans la fenêtre de 24 heures de ManyChat,",
     "Because here, not only can you let the AI write whatever follow-up you want, within ManyChat's 24-hour window,"),
    (282, 286, "mais vous pouvez aussi l'écrire vous-même, ou même enregistrer une note vocale, pour que les follow-ups soient encore plus personnalisés et que la personne ne se doute absolument pas qu'une IA se cache derrière les messages.",
     "you can also write it yourself, or even record a voice note, so your follow-ups feel even more personal and the person has absolutely no idea there's an AI behind the messages."),
    (287, 290, "Et ici, vous avez les settings, tout ce qui vous permet de gérer, par exemple, le délai que l'IA va mettre pour répondre.",
     "And here you have the settings, everything that lets you control, for example, how long the AI waits before it replies."),
    (291, 294, "Là, il est réglé sur 45 secondes, et on verra tout à l'heure, pendant le test, qu'il attend bien 45 secondes.",
     "Right now it's set to 45 seconds, and you'll see in the test in a moment that it really does wait 45 seconds."),
    (295, 297, "Vous pouvez aussi mettre en pause ou supprimer votre setter si vous en avez envie.",
     "You can also pause or delete your setter whenever you want."),
    (298, 298, "Mais vous avez aussi des règles de sécurité.",
     "But you've also got safety rules."),
    (299, 301, "Par exemple, vous allez pouvoir lui dire d'arrêter de parler à partir du moment où la personne parle, par exemple, de remboursement,",
     "For example, you can tell it to stop talking the moment the person brings up, say, a refund,"),
    (302, 306, "ou de quelque chose dont vous n'avez pas envie de parler, quand vous ne voulez pas que l'IA fasse ce choix-là et prenne le risque d'aborder ces sujets.",
     "or something you don't want to talk about, when you don't want the AI making that call and risking a conversation on those topics."),
    (307, 309, "Donc c'est super intéressant. Et vous avez ici une inbox dans laquelle vous allez retrouver tous les messages.",
     "So that's super useful. And here you have an inbox with all your messages."),
    (310, 312, "Et comme vous pouvez le voir, on a ici les messages que l'on a envoyés pendant le test.",
     "And as you can see, here are the messages we sent during the test."),
    (313, 316, "Vous pouvez donc voir directement à quoi ça ressemble, et vous allez bien sûr pouvoir prendre la main sur le lead si vous en avez envie.",
     "So you can see exactly what it looks like, and of course, you can take over the lead whenever you feel like it."),
    (317, 319, "Si vous voulez gérer vos leads à la main, vous pouvez récupérer la conversation absolument quand vous le voulez.",
     "If you'd rather handle your leads yourself, you can take back the conversation anytime you want."),
    (320, 322, "Donc maintenant, il est temps de voir si ça fonctionne réellement sur notre compte Instagram.",
     "So now it's time to see if this actually works on our Instagram account."),
    (323, 324, "Et c'est parti, on se rejoint directement sur mon compte Instagram, ici.",
     "Let's go, I'll meet you right over on my Instagram account."),
    (325, 329, "Donc on peut voir que, je vais décaler mon image, on peut voir que juste ici se trouve le compte Instagram qui est relié à ManyChat, et nous allons lui envoyer un premier message.",
     "So you can see, let me move my facecam, you can see that right here is the Instagram account connected to ManyChat, and we're going to send it a first message."),
    (330, 330, "Donc nous allons écrire, par exemple : « About ecom ».",
     "So we'll type, for example: About e-com."),
    (331, 333, "Tout simplement, nous allons envoyer ce message, attendre la réponse et voir ce que notre setter répond.",
     "We'll simply send this message, wait for the reply, and see what our setter says."),
    (334, 336, "On voit qu'il nous demande si j'ai déjà commencé à vendre ou si je débute tout juste.",
     "We can see it's asking whether I've already started selling or if I'm just getting started."),
    (337, 339, "Donc je lui dis que j'ai déjà fait un million. Il me demande ce que je vends actuellement.",
     "So I tell it I've already made a million. Then it asks what I'm currently selling."),
    (340, 340, "Je lui réponds : des produits pour chiens.",
     "I answer: dog products."),
    (341, 344, "Ce à quoi il me répond : « C'est une bonne niche. Depuis combien de temps est-ce que tu fais de l'e-com ? »",
     "To which it replies: That's a great niche. How long have you been doing e-com?"),
    (345, 345, "Je lui réponds : deux ans.",
     "I answer: two years."),
    (346, 347, "« Est-ce que tu as déjà essayé de trouver des produits gagnants ? »",
     "Have I tried finding winning products?"),
    (348, 352, "Du coup, je lui dis que je regarde actuellement Pinterest Trends, et là, il me dit : « Ah, mais qu'est-ce qui te retient, à ton avis, d'atteindre les 10k par mois avec ta boutique e-com ? »",
     "So I tell it I'm currently checking Pinterest Trends, and then it says: Ah, but what do you think is holding you back from hitting 10K a month with your e-com store?"),
    (353, 355, "Donc je lui dis : les bonnes sources, et peut-être les compétences pour faire de meilleures ads ou de meilleures boutiques.",
     "So I tell it: the right sources, and maybe the skills to make better ads or better stores."),
    (356, 360, "Il me répond qu'il pourrait m'aider à atteindre les 10 000 euros par mois, mais me demande d'abord si j'ai 3 000 euros de côté à investir dans ce projet.",
     "It replies that it could help me reach 10,000 euros a month, but first asks if I have 3,000 euros set aside to invest in this project."),
    (361, 363, "Je lui dis : oui, pourquoi pas. Il me fait un récap et me dit que la prochaine étape, c'est un appel de 30 minutes.",
     "I say yes, why not. It gives me a recap and tells me the next step is a 30-minute call."),
    (364, 364, "Je lui dis que je suis OK.",
     "I tell it I'm in."),
    (365, 365, "Il m'envoie le lien.",
     "It sends me the link."),
    (366, 369, "Je lui dis que j'ai pris mon appel pour le lendemain à 4 heures de l'après-midi, et il me dit : « Parfait, on se voit à 4 heures. »",
     "I tell it I booked my call for the next day at 4 p.m., and it says: Perfect, see you at 4."),
    (370, 372, "Le prompt utilisé n'a demandé que cinq minutes de travail.",
     "The prompt we used only took five minutes to put together."),
    (373, 374, "Alors imaginez : si vous peaufinez votre script de setting, vous pouvez avoir des résultats démentiels.",
     "So imagine: if you fine-tune your setting script, you can get insane results."),
    (375, 379, "Et le plus intéressant dans tout ça, c'est que si on retourne sur notre application ManySetter, ici, et que vous allez directement dans l'Inbox, qu'est-ce que vous pouvez voir ?",
     "And the most interesting part is, if we go back to our ManySetter app here and head straight into the Inbox, what do you see?"),
    (380, 380, "Vous pouvez voir directement ici : « Booked ».",
     "You can see it right here: Booked."),
    (381, 383, "Donc vous allez pouvoir consulter directement les statistiques et comprendre ce qui s'est passé.",
     "So you can check the stats directly and understand exactly what happened."),
    (384, 385, "Vous pouvez voir la conversation, vous pouvez même la reprendre vous-même, donc c'est génial.",
     "You can see the conversation, you can even take it over yourself, so it's awesome."),
    (386, 387, "Synchronisez ManySetter avec ManyChat, et vous ne perdrez plus jamais aucun lead.",
     "Sync ManySetter with ManyChat, and you'll never lose a single lead again."),
    (388, 388, "J'espère que cette vidéo vous aura plu.",
     "I hope you enjoyed this video."),
    (389, 390, "Si vous avez des questions, n'hésitez pas à me les poser en commentaire.",
     "If you have any questions, feel free to ask me in the comments."),
    (391, 391, "J'espère que cette vidéo vous aura plu.",
     "Hope you enjoyed it."),
    (394, 394, "Merci à tous, et à la prochaine !",
     "Thanks, everyone, and see you next time!"),
]
